### ISSUE TITLE
Quick button freezes TVRename

### ISSUE THREAD

**Issue by WeyldFalcon** [TV-Rename/tvrename#384] opened 2018-05-04 00:41 UTC
# Expected Behaviour

A quick scan to occur

# Current Behaviour

software freezes (Not Responding)

# Failure Information

What information will help?

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Click Quick button under Scan Tab
2. Wait
3. Click the edge to move it around to see why nothing is happening
4. (Not Responding) shows up after software name in the header
5. Closing the program takes a good 15 sec

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.
*versions of TVRename: 2.3.2, 2.4.1, 2.4.2 RC3
* Firmware Version:
* Operating System: Windows 10
* SDK version:
* Toolchain version:

## XML Files

I tried but it said We don't support that file type
so I tried zipping them and adding them and got the same answer

**Comment by MarkSummerville** [comment] 2018-05-04 00:49
Hi,

Couple of questions

Does this happen every time you run tv rename? 

What are the last few lines in the log file? Is there still information being added to the log file? 

If you change the extension to .txt for the log and xml files you should be able to post them

Cheers

**Comment by WeyldFalcon** [comment] 2018-05-04 00:58
all 6 times i have tried so far

here is the section of the log I assume you are looking for

2018-05-03 20:42:26|FATAL| UNHANDLED EXCEPTION IN DOWNLOAD THREAD System.AggregateException: One or more errors occurred. ---> System.OverflowException: Value was either too large or too small for an Int32.
   at System.Convert.ToInt32(Int64 value)
   at System.Int64.System.IConvertible.ToInt32(IFormatProvider provider)
   at System.Convert.ToInt32(Object value, IFormatProvider provider)
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at TVRename.TheTVDB.<>c__DisplayClass48_0.<GetUpdates>b__0(JObject jsonResponse)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at TVRename.TheTVDB.GetUpdates()
   at TVRename.TVDoc.Downloader()
---> (Inner Exception #0) System.OverflowException: Value was either too large or too small for an Int32.
   at System.Convert.ToInt32(Int64 value)
   at System.Int64.System.IConvertible.ToInt32(IFormatProvider provider)
   at System.Convert.ToInt32(Object value, IFormatProvider provider)
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at TVRename.TheTVDB.<>c__DisplayClass48_0.<GetUpdates>b__0(JObject jsonResponse)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---
 
2018-05-03 20:43:29|INFO| ******************************* 
[2.1.7z.txt](https://github.com/TV-Rename/tvrename/files/1973073/2.1.7z.txt)

**Comment by MarkSummerville** [comment] 2018-05-04 01:40
Seems like a duplicate of #385

**Comment by WeyldFalcon** [comment] 2018-05-04 16:12
This is different than #385, #384 has been happening since I upgraded from 2.1 to 2.3.2. #384 is new as of last night. To be fair Quick button did not exist in 2.1 so I was excited to try it.

**Comment by MarkSummerville** [comment] 2018-05-04 22:29
OK- so for this one. What happens? Just complete a freeze? Nothing in the logs?

**Comment by WeyldFalcon** [comment] 2018-05-06 00:16
* The search folder is set to the 3 folders that I have unsorted files landing in. TV, TV Old, and Cartoons.
* I don't see how to turn off Auto Add, I found the Bulk/Auto Add tab in Preferences but there does not seem to be  a way to turn it off just 2 checkboxes for Only Include Folders containing Video files (unchecked) and Ignore Recycle Bin (unchecked). And then a section for Movie Terms to ignore and Suffixes to ignore, but nowhere do I see how to turn it off.
* Full scan does a full scan, Recent seems to only to recent files, Quick is the only one that freezes TVRename

**Comment by MarkSummerville** [comment] 2018-05-06 07:42
I'll add some logging to the next version to shed a little more light on what's going on. I suspect that if you leave it long enough then it'll work. A quick scan will take a look at the search folders (and any subfolders) to see what's been downloaded recently. If you have a vast structure on a network dive then that may take a while. The search folders should not really overlap with your download ones ideally

**Comment by MarkSummerville** [comment] 2018-05-06 07:43
Maybe try setting your search folders to c:/downloads and see whether that frees up the quick scan?

**Comment by MarkSummerville** [comment] 2018-05-07 09:05
@WeyldFalcon Did changing the search folder help free up the Quick Search?

**Comment by WeyldFalcon** [comment] 2018-05-08 00:07
Yes, that worked. I see the problem. I was placing the file in the tv show folders which was too much to scan. I get it now, my mistake, time to go change all of my ripping tools to aim at one location.

**Comment by MarkSummerville** [comment] 2018-05-08 00:10
Great. You can still specify multiple locations `c:/new TV` ; `d:/downloads/TV` and `f:/recent` for example. Only restriction is that they are distinct locations from the main library.

Good luck

**Closed by MarkSummerville** 2018-05-08 00:10 UTC
