### ISSUE TITLE
4.7.2 doesn't work on Win 10 at all for me

### ISSUE THREAD

**Issue by SAH7777** [TV-Rename/tvrename#926] opened 2022-06-29 01:37 UTC
keeps giving me the needs .NET stuff warning (doesn't launch tv rename) on Win 10, even after installing everything from the dowload link given in the warning popup:  

https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=6.0.0&arch=x64&rid=win10-x64&gui=true

downloaded both versions in both x86 and x64, and still didn't work even after restarting PC with all that freshly installed

sorry, i can't spend more time testing tv rename betas

thanks for tv rename though!

i'm switching bak to 4.7.1 and then chaning to the main/full release (no beta) update stream

thx again

**Comment by coex177** [comment] 2022-06-29 03:42
I have this same thing going on strangely. I also tried installing the 7.0 SDK preview to see if this would resolve the issue but no good. Going back to 4.7.1 works correctly after it is reinstalled, but 4.7.2 keeps giving this same error.

**Comment by SAH7777** [comment] 2022-06-29 03:46
ur changes from .1 to .2 probably references something from the newest .net api, so check on that

why the os is not detecting installed .net v6 (when tv rename .2 is launched) is another mystery

sorry i'm not a serious Windows programmer

**Comment by SirSparkles** [comment] 2022-06-29 03:47
Does it give you any errors in the logs? There a quite a few fundamental changes between 4.7.1 and 4.7.2 so may take a few tries to get working again. The folder structures are different, so it must be looking for some files in the wrong locations...

**Comment by SAH7777** [comment] 2022-06-29 03:48
sorry i already rolled back to 4.7.1 and relaunched/retested-as-working and that wipes the tv rename logs (i think)

**Comment by SAH7777** [comment] 2022-06-29 03:52
ps: 4.7.1 is pretty solid (for me, and i like it), so no real rush to fix it, can take ur time to find the problematic .net reference

best wishes

**Comment by coex177** [comment] 2022-06-29 03:59
I checked mine and no updates are made to the log files. It doesn't even really load anything in the application at all I don't think. The error comes up immediately when clicking on the application icon, there is no time between clicking and the error coming up, it doesn't even feel like the application is being run at all. 
<img width="202" alt="image" src="https://user-images.githubusercontent.com/66715708/176348494-f2977e19-0dc5-4bfc-b6b2-9c6a145da439.png">

**Comment by SirSparkles** [comment] 2022-06-29 04:03
Can you see whether the following files are in 

C:\Program Files (x86)\TVRename\runtimes\win-x64\native

/locals directory
libcef.dll
icudtl.dat
CefSharp.BrowserSubprocess.exe
CefSharp.BrowserSubprocess.runtimeconfig.json
(among others)

Does the log mention the following lines? and do the paths line up with real ones?

2022-06-28 23:55:46|INFO| Updated path for BrowserSubprocess: C:\Program Files (x86)\TVRename\runtimes\win-x64\native\CefSharp.BrowserSubprocess.exe 
2022-06-28 23:55:46|INFO| Updated path for LocalesDirPath: C:\Program Files (x86)\TVRename\runtimes\win-x64\native\locales 
2022-06-28 23:55:46|INFO| Updated path for ResourcesDirPath: C:\Program Files (x86)\TVRename\runtimes\win-x64\native 
2022-06-28 23:55:46|INFO| Checking for CEF dependencies C:\Program Files (x86)\TVRename\runtimes\win-x64\native 
2022-06-28 23:55:46|INFO| Dependencies all found

**Comment by SirSparkles** [comment] 2022-06-29 04:04
Did you load the framework it was asking for? (may require a restart). I'll install it in the installer if it proves to be the issue

**Comment by SAH7777** [comment] 2022-06-29 04:13
sorry i don't know i just installed the stuff it wanted (guessed and did all 4 variants, see comment above about variants) and restarted my pc a few times, but it kept spitting out that error (the same error you screenshotted)


re logs, dude, u realise that i'm staying on 4.7.1 for now right (i actually want to use tv rename today), but here is the top of the log:
2022-06-29 13:12:26|FATAL| TV Rename 4.7.1 logging started on Microsoft Windows NT 6.2.9200.0, 64 Bit OS, 64 Bit Process 4.0.30319.42000 Interactive with args:  
2022-06-29 13:12:26|INFO| Copyright (C) 2022 TV Rename 
2022-06-29 13:12:26|INFO| This program comes with ABSOLUTELY NO WARRANTY; This is free software, and you are welcome to redistribute it under certain conditions 
2022-06-29 13:12:26|WARN| Updated path for Assembly: C:\Program Files (x86)\TVRename\x64\CefSharp.Core.Runtime.dll 
2022-06-29 13:12:26|INFO| Updated path for BrowserSubprocess: C:\Program Files (x86)\TVRename\x64\CefSharp.BrowserSubprocess.exe 
2022-06-29 13:12:26|INFO| Updated path for LocalesDirPath: C:\Program Files (x86)\TVRename\x64\locales 
2022-06-29 13:12:26|INFO| Updated path for ResourcesDirPath: C:\Program Files (x86)\TVRename\x64 
2022-06-29 13:12:26|INFO| Dependencies all found 


re C:\Program Files (x86)\TVRename\runtimes\win-x64\native
i have the files
but not CefSharp.BrowserSubprocess.runtimeconfig.json

**Comment by SAH7777** [comment] 2022-06-29 04:16
![image](https://user-images.githubusercontent.com/84061264/176350447-2c09bfb5-c1f4-4541-ba6c-b91346c5662e.png)

**Comment by SirSparkles** [comment] 2022-06-29 04:23
ok - looks like the installer is not copying CefSharp.BrowserSubprocess.runtimeconfig.json correctly

It's available at https://github.com/TV-Rename/tvrename/blob/master/CefSharp.BrowserSubprocess.runtimeconfig.json

@coex177  if you are able to download and manually put it into the location and retry - that would let us know whether installing it too would help

**Comment by coex177** [comment] 2022-06-29 05:22
Greetings! Sorry it took me so long to reply to this, I was doing a lot of testing to try and figure out the issue. That .json file was indeed missing, but copying it to the location did not actually fix the error. I discovered that correcting the error itself involved installing the .NET SDK 6.0. I had only had the runtime installed but was still getting the error above, **until** I installed the SDK. Once I installed the SDK, TVRename actually opened, but I received another error regarding installing the .net core (which was installed). After putting the .json file in the proper place, that .net core error also went away and the application now loads correctly. 

I see that during all of this you had pushed out a 4.7.4 which I installed to test, and it faces the same need to have the SDK installed. I'm assuming that the 4.7.4 puts the .json file in the proper location, but the need for the SDK still remains, as when I uninstall the SDK, I get the same error above when I try running TVRename. Reinstalling the SDK removes the error. So there is something in the SDK that the application apparently needs to run correctly. I hope this helps and makes some sense.

**Comment by SirSparkles** [comment] 2022-06-29 05:25
@coex177 Thank you so much for contributing and helping.

Yes 4.7.4 will fix the json issue. (but doesn't try to install '.NET SDK 6.0') I'm surprised the Runtime is not enough. Next job is to to get the installer to check and install it as well.

Thanks again - has really helped me.

**Comment by coex177** [comment] 2022-06-29 05:29
@SirSparkles Happy to help, thanks for everything you do with this application. It's really a life saver for people like myself. Very appreciated.

**Comment by BacchusFLT** [comment] 2022-06-29 14:11
I also have the same issue that the program calls for downloding .NET. 4.7.1 launched fine, but 4.7.2 did not and I can confirm that 4.7.4 also did NOT solve the problem for me.

I removed the files in the directory "AppData\Roaming\TVRename\log\" but there was no log recreated.


![image](https://user-images.githubusercontent.com/28536010/176457966-2494e36b-9dee-4af9-b923-3670740af380.png)

**Comment by SirSparkles** [comment] 2022-06-29 14:36
Did you install the sdk from here?

**Comment by SirSparkles** [comment] 2022-06-29 14:38
or here https://dotnet.microsoft.com/en-us/download

**Comment by Chlorel** [comment] 2022-06-29 15:49
Finally 4.7.4 run's on windows 10 ... 
But why do i have to install the hosting bundle ? ( i have try desktop app, console app in x64 and x86 without any succes before )

**Comment by SirSparkles** [comment] 2022-06-30 01:38
@Chlorel - Not really sure yet. It's unclear whether the SDK installs the same DLLs in a different place (which means TVR can pick them up) or whether it installs separate stuff that is not available in the runtime. TVR should only need the runtime to be installed as far as I can tell.

Also we need to improve the TVR installer to make the needed installations (C++ runtime and the .net core runtime) so that we do not need users to install these separately. Still a work in progress

**Comment by BacchusFLT** [comment] 2022-06-30 10:23
@SirSparkles I downloaded from the link the program offers when it detects that all the dependencies aren't there ...

**Comment by SirSparkles** [comment] 2022-06-30 13:28
@BacchusFLT - can you try this one please: https://dotnet.microsoft.com/en-us/download/visual-studio-sdks
and make sure you have 4.7.4 installed

**Comment by BacchusFLT** [comment] 2022-07-01 13:10
@SirSparkles 

I have Windows 10 (64bit) Pro (19044)  + TVRename 4.7.4

Downloaded x64 for Windows x64 Runtime is **still a no go**.
https://dotnet.microsoft.com/en-us/download/visual-studio-sdks

Downloaded the x64 version of Visual Studio 2022 SDK - **SUCCESS**

Not sure what did the trick, but asking for the full SDK is asking a lot (and also the error message is pointing to downloading the runtime - not the SDK)

**Comment by maxthiel** [comment] 2022-10-23 20:06
Hello,

I've had the same experience on Win10 with version 4.8.0
Installing the SDK solves the issue.

**Comment by rrrevin** [comment] 2022-12-24 14:35
I had the same issue with 4.8.4. I needed both dotnet-runtime-6.0.12-win-x64.exe and aspnetcore-runtime-6.0.12-win-x64.exe to get things going.

**Comment by TheOlympicon** [comment] 2023-02-11 22:56
is it worth using a self-contained PublishProfile at build-time to include all the prerequisite .NET and external dependencies?

**Comment by SirSparkles** [comment] 2023-02-12 01:04
I have never been able to work out who it needs the SDK and not the runtime. Also have not worked out to install it as part of the installation (as we did with .net framework) 

would love some help if anyone is an expert in the best, simplest way to do this.

**Comment by TheOlympicon** [comment] 2023-02-13 15:58
I'll submit a PR if you like. you can discard it if you're not a fan.

It includes all the .NET libraries it needs inside its executable (while leaving external libraries separate), but that makes the executable 175MB in my testing... 

using dotnet publish, there's a <PublishTrimmed> tag, but the publish process throws errors in vs2022 relating to Microsoft.WebTools.Shared.Exceptions.

**Comment by SirSparkles** [comment] 2023-05-22 00:12
Hey @TheOlympicon - sorry completely missed your offer.

I would **love** that - now that TVDB have broken the v3 API, we need people to upgrade to 4.9.5 and many people are getting the dependencies problem. 175mb is not too big (its 150 anyway)

**Comment by TheOlympicon** [comment] 2023-05-22 19:28
Okay. I've created the publishprofile in the project. I can generate a pull request for that.

Integrating that with the build is a bit muddy for me. I'm not familiar with Appveyor at all. I could probably do with a quick chat about it at before I commit anything so I don't mess everything up!

**Comment by TheOlympicon** [comment] 2023-05-27 17:43
publishprofile generated. do you need to grant me access to the repo to create a new branch and commit?

**Comment by SirSparkles** [comment] 2023-05-29 10:16
You should be able to create a PR

**Comment by SirSparkles** [comment] 2023-05-31 01:01
@TheOlympicon  Thanks v much - have merged it in - we'll see what happens on the next aitomated build

**Closed by SirSparkles** 2023-05-31 01:01 UTC
