### ISSUE TITLE
Merging episodes breaks naming for following episodes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TV-Rename/tvrename#73] opened 2015-09-30 11:42 UTC
```
What steps will reproduce the problem?
1. Merge episode 1 & 2 of Heroes season 4
2.
3.

What is the expected output? What do you see instead?
- Merge the episodes, name the rest accordingly.  Instead, the name of 
episode 2 (Jump, Push, Fall) is applied to Episode 3, the name of episode 3 
(Ink) is applied to Episode 4, and so on.  Merging the first two episodes 
seems to break the naming of all the following episodes.


What version of the product are you using? On what operating system?
- 2.2.0a7, Windows 7


Please provide any additional information below.


```

Original issue reported on code.google.com by `coveb...@gmail.com` on 7 Oct 2009 at 8:09

**Comment by JoeBiellik** [comment] 2018-02-28 16:31
I can't reproduce this - can anyone else?

**Comment by Andy-ABTec** [comment] 2018-02-28 17:57
I have Heroes S4 on DVD...

Take a look at TheTVDB. The Broadcast version has 19 episodes though it looks as if 1 and 2 were aired as a double from the air date episode 3 being "Ink".

The DVD version lists 18 episodes, 1 and 2 labeled as 1.1 and 1.2 with the same episode names and episode 2 being "Ink" TVRename gets really confused if I change from one to the other.

Episode 1/1.1 and 2/1.2 is a genuine double episode, not two singles played back to back.

Not sure what can be done about this - my gut says its a tvdb problem but the season is locked.

Happy to test whatever you wish...

**Comment by JoeBiellik** [comment] 2018-02-28 18:25
I don't have any issue switching between DVD order but with or without it I get the same result. If I mark S04E01 and E02 and merged I get  ``E01-E02 - Orientation + Jump, Push, Fall`` and ``E03 - Ink``. I can't reproduce the original issue of E04 being named ``Ink``.

**Comment by Andy-ABTec** [comment] 2018-02-28 20:11
Ok I'll have a play...

**Comment by Andy-ABTec** [comment] 2018-03-01 07:51
Neither can I...

**Closed** 2018-03-01 08:39 UTC
Labels: Priority-Medium, Retest needed, Type-Defect, auto-migrated
