### ISSUE TITLE
Bug: WebBrowser exception raised during launch

### ISSUE THREAD

**Issue by StuartMeeks** [TV-Rename/tvrename#636] opened 2019-05-16 00:22 UTC
# Expected Behaviour
TVRename launches

# Current Behaviour
After splash screen disappears and main screen appears, exception is raised regarding loading the web browser control in an STA

# Failure Information
Exception raised as My Shows tab is rendered:
System.Threading.ThreadStateException: ActiveX control '8856f961-340a-11d0-a96b-00c04fd705a2' cannot be instantiated because the current thread is not in a single-threaded apartment.
   at System.Windows.Forms.WebBrowserBase..ctor(String clsidString)
   at System.Windows.Forms.WebBrowser..ctor()
   at TVRename.Forms.UpdateNotification.InitializeComponent()
   at TVRename.Forms.UpdateNotification..ctor(Release update)
   at TVRename.UI.NotifyUpdates(Release update, Boolean showNoUpdateRequiredDialog, Boolean inSilentMode)
   at TVRename.UI.<UpdateTimer_Tick>d__248.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

## Steps to Reproduce
This happens every time I launch v2.8.2 of TVRename however it was working when I first installed, but has only started failing today. Will continue to investigate.

## Context
* Operating System: Windows 10 1903 (OS Build 18362.86)
* Are you using the windows version or command line version? Windows Version

I did notice that a Windows Update for .NET 4.8 was recently installed on my system. I also installed the .NET Framework 4.8 Developer Pack recently too.

## XML Files
Will supply if required.

## Log Files
[TVRename.log](https://github.com/TV-Rename/tvrename/files/3184898/TVRename.log)

## Error messages
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Threading.ThreadStateException: ActiveX control '8856f961-340a-11d0-a96b-00c04fd705a2' cannot be instantiated because the current thread is not in a single-threaded apartment.
   at System.Windows.Forms.WebBrowserBase..ctor(String clsidString)
   at System.Windows.Forms.WebBrowser..ctor()
   at TVRename.Forms.UpdateNotification.InitializeComponent()
   at TVRename.Forms.UpdateNotification..ctor(Release update)
   at TVRename.UI.NotifyUpdates(Release update, Boolean showNoUpdateRequiredDialog, Boolean inSilentMode)
   at TVRename.UI.<UpdateTimer_Tick>d__248.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

## Screenshots or videos of the issue
![image](https://user-images.githubusercontent.com/11793922/57817776-49fb1d80-77c4-11e9-91aa-b2a1dcf252f0.png)

**Comment by MarkSummerville** [comment] 2019-05-16 04:37
Duplicate of #635 - Closing

Just need to update to the latest

**Closed** 2019-05-16 04:39 UTC

**Comment by smuman** [comment] 2019-05-21 16:31
Hi, i'm using 2.8.3 and got the same error!
[tvrename Fehlermeldung.txt](https://github.com/TV-Rename/tvrename/files/3203561/tvrename.Fehlermeldung.txt)
