### ISSUE TITLE
TVRename do not do he's job in 2.8.0 .. but does it in 2.7.1 .. just not see or move or rename files

### ISSUE THREAD

**Issue by Chlorel** [TV-Rename/tvrename#623] opened 2019-03-13 07:10 UTC
Hi, 
Just noticed ( and can redo the noticed problem ) some time ( but not every time ) TVRename 2.8.0 does not 'see' new incommes file ... and does not move, or rename file .. But when i go back to 2.7.1 ... TVRename does the job ..
My caps and logs show you the difference when i just do a 'scan' on the serie 'Games Of Thrones ...
I add the 2 caps ... and the 2 log files

![TVRename 2 8 0](https://user-images.githubusercontent.com/8551213/54259859-66ca6900-4567-11e9-9988-25770250d7ef.PNG)
[TVRename.2.8.0.log](https://github.com/TV-Rename/tvrename/files/2960159/TVRename.2.8.0.log)
![TVRename 2 7 1](https://user-images.githubusercontent.com/8551213/54259860-6762ff80-4567-11e9-88e6-b1d99812da21.PNG)
[TVRename.2.7.1.log](https://github.com/TV-Rename/tvrename/files/2960160/TVRename.2.7.1.log)

**Comment by Chlorel** [comment] 2019-03-13 07:14
I notice too 2.8.0 do not give me the missing files ( from season 7 ) and do not see the season 6 that is currently in download process with qbtorrent ...

**Comment by Chlorel** [comment] 2019-03-13 07:17
TVRename 2.8.0 show me the same blank windows as in 1rst message ...
When TVRename 2.7.1 show's me this one ...

![TVRename 2 7 1_(2)](https://user-images.githubusercontent.com/8551213/54260099-44851b00-4568-11e9-98b3-adab6d2aa09f.PNG)

**Comment by MarkSummerville** [comment] 2019-03-13 10:29
Have you tired the latest 'master' code?

I think the problem is already fixed

**Comment by Chlorel** [comment] 2019-03-13 10:46
I tryed some versions ...
the 2.7.1 is my extra modified one that allow me tp switch from collection to collection ...
I tryed original 2.7.1 ( with code from zip file delivered on release page )
I tryed 2.8.0 originale ( again from release page )
I tryed the last code from github too ... ( the log / screens are from the lastest code )

but i can try to do a blank code download and compile it :)

**Comment by Chlorel** [comment] 2019-03-13 11:05
Finaly with a need pull request for your last changes ... look's like 2.8.0 see the files now 

![TVRename 2 8 0 LS](https://user-images.githubusercontent.com/8551213/54274295-0861b280-4588-11e9-9a1c-4a4687690d78.PNG)

Helpfully i take more time to download 13.5Go torrents slower as 5 Go torrents :)

You are right, you fixed to problem :)


Between ... is it possible to add a 'delete show' button to missing folder windows ?

**Comment by MarkSummerville** [comment] 2019-03-13 11:19
Great - I'll release it as 2.8.1

**Comment by MarkSummerville** [comment] 2019-03-13 11:19
Can we close this issue?

**Comment by Chlorel** [comment] 2019-03-13 11:31
sure we can close

**Closed** 2019-03-13 11:35 UTC
