### ISSUE TITLE
Missing frameworks for .NET

### ISSUE THREAD

**Issue by 555five** [TV-Rename/tvrename#930] opened 2022-07-01 06:24 UTC
After upgrading from version 4.71 to 4.74, I see the message:

![framework](https://user-images.githubusercontent.com/98145144/176836200-3107ac9a-c5b1-4029-956e-37d6d3ddfe3e.jpg)

I follow the link and download / install  "windowsdesktop-runtime-6.0.6-win-x64.exe", however I still get the same message when launching TV Rename.  
Are there different framework componenets that might be missing? 

Thanks.

**Comment by SirSparkles** [comment] 2022-07-02 00:08
Duplicate of #926 
https://dotnet.microsoft.com/en-us/download/visual-studio-sdks is the one to download. Just investigating why this is the case at the moment

**Closed by SirSparkles** 2022-07-02 00:08 UTC
